In [ ]:
import sys
import os
import pandas as pd
import numpy as np


def error_exit(msg):
    print("Error:", msg)
    sys.exit(1)


def parse_weights_impacts(weights_str, impacts_str):
    # Must be comma separated
    if "," not in weights_str or "," not in impacts_str:
        error_exit("Weights and impacts must be separated by ',' (comma).")

    weights = weights_str.strip().split(",")
    impacts = impacts_str.strip().split(",")

    # Strip spaces
    weights = [w.strip() for w in weights]
    impacts = [i.strip() for i in impacts]

    # Convert weights to float
    try:
        weights = [float(w) for w in weights]
    except:
        error_exit("Weights must be numeric values separated by commas.")

    # Check impacts only + or -
    for i in impacts:
        if i not in ["+", "-"]:
            error_exit("Impacts must be either '+' or '-' only.")

    return weights, impacts


def topsis(input_file, weights_str, impacts_str, output_file):
    # File not found
    if not os.path.exists(input_file):
        error_exit(f"File not found: {input_file}")

    # Read CSV
    try:
        df = pd.read_csv(input_file)
    except Exception as e:
        error_exit(f"Unable to read input file. {str(e)}")

    # Must contain >= 3 columns
    if df.shape[1] < 3:
        error_exit("Input file must contain three or more columns.")

    # Extract decision matrix (2nd to last columns)
    data = df.iloc[:, 1:].copy()   # from 2nd column to last
    n_cols = data.shape[1]

    # Parse weights and impacts
    weights, impacts = parse_weights_impacts(weights_str, impacts_str)

    # Check number of weights/impacts equals number of numeric columns
    if len(weights) != n_cols or len(impacts) != n_cols:
        error_exit("Number of weights, impacts and columns (from 2nd to last) must be the same.")

    # Check numeric values only in 2nd to last columns
    for col in data.columns:
        # Convert column to numeric; if error -> non numeric exists
        try:
            data[col] = pd.to_numeric(data[col])
        except:
            error_exit(f"Non-numeric value found in column '{col}'. Only numeric values allowed from 2nd to last columns.")

    # ---------- TOPSIS Steps ----------
    matrix = data.to_numpy(dtype=float)

    # Step 1: Normalize the decision matrix
    norm = np.sqrt((matrix ** 2).sum(axis=0))
    if np.any(norm == 0):
        error_exit("Normalization failed because a column has all zeros.")
    normalized = matrix / norm

    # Step 2: Weighted normalized decision matrix
    weights = np.array(weights, dtype=float)
    weighted = normalized * weights

    # Step 3: Determine Ideal Best and Ideal Worst
    ideal_best = np.zeros(n_cols)
    ideal_worst = np.zeros(n_cols)

    for j in range(n_cols):
        if impacts[j] == "+":
            ideal_best[j] = np.max(weighted[:, j])
            ideal_worst[j] = np.min(weighted[:, j])
        else:  # "-"
            ideal_best[j] = np.min(weighted[:, j])
            ideal_worst[j] = np.max(weighted[:, j])

    # Step 4: Distances from ideal best and ideal worst
    dist_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    # Step 5: TOPSIS score
    score = dist_worst / (dist_best + dist_worst)

    # Rank (higher score => better rank)
    rank = score.argsort()[::-1] + 1   # descending

    # Output
    df["Topsis Score"] = score
    df["Rank"] = pd.Series(rank)

    # Save
    try:
        df.to_csv(output_file, index=False)
    except Exception as e:
        error_exit(f"Unable to write output file. {str(e)}")

    print(f"TOPSIS completed successfully ✅ Output saved to: {output_file}")


if __name__ == "__main__":
    # Must have exactly 4 parameters (program + 4 args => total 5)
    if len(sys.argv) != 5:
        print("Usage:")
        print("python topsis.py <InputDataFile> <Weights> <Impacts> <OutputResultFileName>")
        print('Example: python topsis.py data.csv "1,1,1,2" "+,+,-,+" output-result.csv')
        sys.exit(1)

    input_file = sys.argv[1]
    weights_str = sys.argv[2]
    impacts_str = sys.argv[3]
    output_file = sys.argv[4]

    topsis(input_file, weights_str, impacts_str, output_file)

Usage:
python topsis.py <InputDataFile> <Weights> <Impacts> <OutputResultFileName>
Example: python topsis.py data.csv "1,1,1,2" "+,+,-,+" output-result.csv

SystemExit: 1

/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
!python topsis.py data.csv "1,1,1,2" "+,+,-,+" output-result.csv

python3: can't open file '/content/topsis.py': [Errno 2] No such file or directory

In [ ]:
import pandas as pd

data = {
    "Fund Name": ["M1","M2","M3","M4","M5","M6","M7","M8"],
    "P1": [0.67,0.60,0.82,0.60,0.76,0.69,0.79,0.84],
    "P2": [0.45,0.36,0.67,0.36,0.58,0.48,0.62,0.71],
    "P3": [6.5,3.6,3.8,3.5,4.8,6.6,4.8,6.5],
    "P4": [42.6,53.3,63.1,69.2,43.0,48.7,59.2,34.5],
    "P5": [12.56,14.47,17.10,18.42,12.29,14.12,16.35,10.64]
}

df = pd.DataFrame(data)
df.to_csv("data.csv", index=False)

df

  Fund Name    P1    P2   P3    P4     P5
0        M1  0.67  0.45  6.5  42.6  12.56
1        M2  0.60  0.36  3.6  53.3  14.47
2        M3  0.82  0.67  3.8  63.1  17.10
3        M4  0.60  0.36  3.5  69.2  18.42
4        M5  0.76  0.58  4.8  43.0  12.29
5        M6  0.69  0.48  6.6  48.7  14.12
6        M7  0.79  0.62  4.8  59.2  16.35
7        M8  0.84  0.71  6.5  34.5  10.64

In [ ]:
%%writefile topsis.py
import sys
import os
import pandas as pd
import numpy as np

def error_exit(msg):
    print("Error:", msg)
    sys.exit(1)

def parse_weights_impacts(weights_str, impacts_str):
    if "," not in weights_str or "," not in impacts_str:
        error_exit("Impacts and weights must be separated by ',' (comma).")

    weights = [w.strip() for w in weights_str.split(",")]
    impacts = [i.strip() for i in impacts_str.split(",")]

    try:
        weights = [float(w) for w in weights]
    except:
        error_exit("Weights must be numeric values separated by commas.")

    for imp in impacts:
        if imp not in ["+", "-"]:
            error_exit("Impacts must be either '+' or '-' only.")

    return weights, impacts

def topsis(input_file, weights_str, impacts_str, output_file):
    if not os.path.exists(input_file):
        error_exit(f"File not found: {input_file}")

    try:
        df = pd.read_csv(input_file)
    except Exception as e:
        error_exit(f"Unable to read input file: {str(e)}")

    if df.shape[1] < 3:
        error_exit("Input file must contain three or more columns.")

    data = df.iloc[:, 1:].copy()
    n_cols = data.shape[1]

    weights, impacts = parse_weights_impacts(weights_str, impacts_str)

    if len(weights) != n_cols or len(impacts) != n_cols:
        error_exit("Number of weights, impacts and columns (from 2nd to last) must be the same.")

    for col in data.columns:
        try:
            data[col] = pd.to_numeric(data[col])
        except:
            error_exit(f"Non-numeric value found in column '{col}'.")

    matrix = data.to_numpy(dtype=float)

    # Normalize
    norm = np.sqrt((matrix ** 2).sum(axis=0))
    if np.any(norm == 0):
        error_exit("Normalization failed because a column has all zeros.")
    normalized = matrix / norm

    # Weighted normalized matrix
    weights = np.array(weights, dtype=float)
    weighted = normalized * weights

    # Ideal best and worst
    ideal_best = np.zeros(n_cols)
    ideal_worst = np.zeros(n_cols)

    for j in range(n_cols):
        if impacts[j] == "+":
            ideal_best[j] = np.max(weighted[:, j])
            ideal_worst[j] = np.min(weighted[:, j])
        else:
            ideal_best[j] = np.min(weighted[:, j])
            ideal_worst[j] = np.max(weighted[:, j])

    # Distances
    dist_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    # Score
    score = dist_worst / (dist_best + dist_worst)

    # Rank
    rank = score.argsort()[::-1] + 1

    df["Topsis Score"] = score.round(4)
    df["Rank"] = rank

    df.to_csv(output_file, index=False)
    print(f"TOPSIS completed ✅ Output saved to: {output_file}")

if __name__ == "__main__":
    if len(sys.argv) != 5:
        print("Usage:")
        print("python topsis.py <InputDataFile> <Weights> <Impacts> <OutputResultFileName>")
        print('Example: python topsis.py data.csv "1,1,1,2" "+,+,-,+" output-result.csv')
        sys.exit(1)

    input_file = sys.argv[1]
    weights_str = sys.argv[2]
    impacts_str = sys.argv[3]
    output_file = sys.argv[4]

    topsis(input_file, weights_str, impacts_str, output_file)

Writing topsis.py

In [ ]:
!python topsis.py data.csv "1,1,1,1,1" "+,+,+,+,+" output-result.csv

TOPSIS completed ✅ Output saved to: output-result.csv

In [ ]:
out = pd.read_csv("output-result.csv")
out

  Fund Name    P1    P2   P3    P4     P5  Topsis Score  Rank
0        M1  0.67  0.45  6.5  42.6  12.56        0.4354     7
1        M2  0.60  0.36  3.6  53.3  14.47        0.3038     3
2        M3  0.82  0.67  3.8  63.1  17.10        0.6269     8
3        M4  0.60  0.36  3.5  69.2  18.42        0.4730     6
4        M5  0.76  0.58  4.8  43.0  12.29        0.4177     4
5        M6  0.69  0.48  6.6  48.7  14.12        0.5234     1
6        M7  0.79  0.62  4.8  59.2  16.35        0.6514     5
7        M8  0.84  0.71  6.5  34.5  10.64        0.5237     2

In [ ]:
from google.colab import files
files.download("output-result.csv")

In [ ]:
import os, shutil

project_name = "topsis-anshika-102317059"
pkg_module = "topsis_anshika_102317059"     # module name must use _

# cleanup if already exists
if os.path.exists(project_name):
    shutil.rmtree(project_name)

os.makedirs(project_name)
os.chdir(project_name)

print("Current directory:", os.getcwd())

Current directory: /content/topsis-anshika-102317059

In [ ]:
os.makedirs(pkg_module)
os.makedirs("tests")

open(f"{pkg_module}/__init__.py", "w").write("__version__ = '1.0.0'\n")

22

In [ ]:
%%writefile topsis_anshika_102317059/topsis_logic.py
import os
import pandas as pd
import numpy as np

class TopsisError(Exception):
    pass

def parse_weights_impacts(weights_str, impacts_str):
    if "," not in weights_str or "," not in impacts_str:
        raise TopsisError("Impacts and weights must be separated by ',' (comma).")

    weights = [w.strip() for w in weights_str.split(",")]
    impacts = [i.strip() for i in impacts_str.split(",")]

    try:
        weights = [float(w) for w in weights]
    except:
        raise TopsisError("Weights must be numeric values separated by commas.")

    for imp in impacts:
        if imp not in ["+", "-"]:
            raise TopsisError("Impacts must be either '+' or '-' only.")

    return weights, impacts

def run_topsis(input_file, weights_str, impacts_str, output_file):
    # File not found
    if not os.path.exists(input_file):
        raise TopsisError(f"File not found: {input_file}")

    # Read
    try:
        df = pd.read_csv(input_file)
    except Exception as e:
        raise TopsisError(f"Unable to read input file: {str(e)}")

    # At least 3 columns
    if df.shape[1] < 3:
        raise TopsisError("Input file must contain three or more columns.")

    data = df.iloc[:, 1:].copy()
    n_cols = data.shape[1]

    weights, impacts = parse_weights_impacts(weights_str, impacts_str)

    if len(weights) != n_cols or len(impacts) != n_cols:
        raise TopsisError("Number of weights, impacts and columns (from 2nd to last) must be the same.")

    for col in data.columns:
        try:
            data[col] = pd.to_numeric(data[col])
        except:
            raise TopsisError(f"Non-numeric value found in column '{col}'.")

    matrix = data.to_numpy(dtype=float)

    # Normalize
    norm = np.sqrt((matrix ** 2).sum(axis=0))
    if np.any(norm == 0):
        raise TopsisError("Normalization failed because a column has all zeros.")
    normalized = matrix / norm

    # Weighted
    weights_arr = np.array(weights, dtype=float)
    weighted = normalized * weights_arr

    # Ideal best/worst
    ideal_best = np.zeros(n_cols)
    ideal_worst = np.zeros(n_cols)

    for j in range(n_cols):
        if impacts[j] == "+":
            ideal_best[j] = np.max(weighted[:, j])
            ideal_worst[j] = np.min(weighted[:, j])
        else:
            ideal_best[j] = np.min(weighted[:, j])
            ideal_worst[j] = np.max(weighted[:, j])

    dist_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    score = dist_worst / (dist_best + dist_worst)
    rank = score.argsort()[::-1] + 1

    df["Topsis Score"] = score.round(4)
    df["Rank"] = rank

    df.to_csv(output_file, index=False)
    return output_file

Writing topsis_anshika_102317059/topsis_logic.py

In [ ]:
%%writefile topsis_anshika_102317059/cli.py
import sys
from .topsis_logic import run_topsis, TopsisError

def main():
    if len(sys.argv) != 5:
        print("Usage:")
        print("topsis <InputDataFile> <Weights> <Impacts> <OutputResultFileName>")
        print('Example: topsis data.csv "1,1,1,2" "+,+,-,+" output-result.csv')
        sys.exit(1)

    input_file = sys.argv[1]
    weights_str = sys.argv[2]
    impacts_str = sys.argv[3]
    output_file = sys.argv[4]

    try:
        run_topsis(input_file, weights_str, impacts_str, output_file)
        print(f"TOPSIS completed ✅ Output saved to: {output_file}")
    except TopsisError as e:
        print("Error:", str(e))
        sys.exit(1)

Writing topsis_anshika_102317059/cli.py

In [ ]:
%%writefile README.md
# TOPSIS Package

This package implements TOPSIS (Technique for Order Preference by Similarity to Ideal Solution) for multi-criteria decision making.

## Installation
```bash
pip install topsis-anshika-102317059

Writing README.md

In [ ]:
%%writefile pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "topsis-anshika-102317059"
version = "1.0.0"
description = "TOPSIS implementation as CLI tool"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name="Anshika", email="anshikaahuja6487@gmail.com"}
]
dependencies = ["pandas", "numpy"]

[project.scripts]
topsis = "topsis_anshika_102317059.cli:main"

Overwriting pyproject.toml

In [ ]:
%%writefile LICENSE
MIT License

Overwriting LICENSE

In [ ]:
!pip install -q build twine

In [ ]:
!python -m build

* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools>=61.0
  - wheel
* Getting build dependencies for sdist...
/tmp/build-env-50p0ddr2/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!

        ********************************************************************************
        Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

        By 2026-Feb-18, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
  corresp(dist, value, root_dir)
running egg_info
creating topsis_anshika_102317059.egg-info
writing topsis_anshika_102317059.egg-info/PKG-INFO
writing dependency_links to topsis_anshika_102317059.egg-info/dependency_links.txt
writing entry points to topsis_anshika_102317059.egg-info/entry_points.txt
writing requirements to topsis_anshika_102317059.egg-info/requires.txt
writing top-level names to topsis_anshika_102317059.egg-info/top_level.txt
writing manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
reading manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
* Building sdist...
/tmp/build-env-50p0ddr2/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!

        ********************************************************************************
        Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

        By 2026-Feb-18, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
  corresp(dist, value, root_dir)
running sdist
running egg_info
writing topsis_anshika_102317059.egg-info/PKG-INFO
writing dependency_links to topsis_anshika_102317059.egg-info/dependency_links.txt
writing entry points to topsis_anshika_102317059.egg-info/entry_points.txt
writing requirements to topsis_anshika_102317059.egg-info/requires.txt
writing top-level names to topsis_anshika_102317059.egg-info/top_level.txt
reading manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
running check
creating topsis_anshika_102317059-1.0.0
creating topsis_anshika_102317059-1.0.0/topsis_anshika_102317059
creating topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying files to topsis_anshika_102317059-1.0.0...
copying LICENSE -> topsis_anshika_102317059-1.0.0
copying README.md -> topsis_anshika_102317059-1.0.0
copying pyproject.toml -> topsis_anshika_102317059-1.0.0
copying topsis_anshika_102317059/__init__.py -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059
copying topsis_anshika_102317059/cli.py -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059
copying topsis_anshika_102317059/topsis_logic.py -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059
copying topsis_anshika_102317059.egg-info/PKG-INFO -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying topsis_anshika_102317059.egg-info/SOURCES.txt -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying topsis_anshika_102317059.egg-info/dependency_links.txt -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying topsis_anshika_102317059.egg-info/entry_points.txt -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying topsis_anshika_102317059.egg-info/requires.txt -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying topsis_anshika_102317059.egg-info/top_level.txt -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
copying topsis_anshika_102317059.egg-info/SOURCES.txt -> topsis_anshika_102317059-1.0.0/topsis_anshika_102317059.egg-info
Writing topsis_anshika_102317059-1.0.0/setup.cfg
Creating tar archive
removing 'topsis_anshika_102317059-1.0.0' (and everything under it)
* Building wheel from sdist
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools>=61.0
  - wheel
* Getting build dependencies for wheel...
/tmp/build-env-q7tzwdiw/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!

        ********************************************************************************
        Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

        By 2026-Feb-18, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
  corresp(dist, value, root_dir)
running egg_info
writing topsis_anshika_102317059.egg-info/PKG-INFO
writing dependency_links to topsis_anshika_102317059.egg-info/dependency_links.txt
writing entry points to topsis_anshika_102317059.egg-info/entry_points.txt
writing requirements to topsis_anshika_102317059.egg-info/requires.txt
writing top-level names to topsis_anshika_102317059.egg-info/top_level.txt
reading manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
* Building wheel...
/tmp/build-env-q7tzwdiw/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!

        ********************************************************************************
        Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

        By 2026-Feb-18, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
  corresp(dist, value, root_dir)
running bdist_wheel
running build
running build_py
creating build/lib/topsis_anshika_102317059
copying topsis_anshika_102317059/topsis_logic.py -> build/lib/topsis_anshika_102317059
copying topsis_anshika_102317059/__init__.py -> build/lib/topsis_anshika_102317059
copying topsis_anshika_102317059/cli.py -> build/lib/topsis_anshika_102317059
running egg_info
writing topsis_anshika_102317059.egg-info/PKG-INFO
writing dependency_links to topsis_anshika_102317059.egg-info/dependency_links.txt
writing entry points to topsis_anshika_102317059.egg-info/entry_points.txt
writing requirements to topsis_anshika_102317059.egg-info/requires.txt
writing top-level names to topsis_anshika_102317059.egg-info/top_level.txt
reading manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'topsis_anshika_102317059.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/topsis_anshika_102317059
copying build/lib/topsis_anshika_102317059/topsis_logic.py -> build/bdist.linux-x86_64/wheel/./topsis_anshika_102317059
copying build/lib/topsis_anshika_102317059/__init__.py -> build/bdist.linux-x86_64/wheel/./topsis_anshika_102317059
copying build/lib/topsis_anshika_102317059/cli.py -> build/bdist.linux-x86_64/wheel/./topsis_anshika_102317059
running install_egg_info
Copying topsis_anshika_102317059.egg-info to build/bdist.linux-x86_64/wheel/./topsis_anshika_102317059-1.0.0-py3.12.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/topsis_anshika_102317059-1.0.0.dist-info/WHEEL
creating '/content/topsis-anshika-102317059/dist/.tmp-4h96855i/topsis_anshika_102317059-1.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'topsis_anshika_102317059/__init__.py'
adding 'topsis_anshika_102317059/cli.py'
adding 'topsis_anshika_102317059/topsis_logic.py'
adding 'topsis_anshika_102317059-1.0.0.dist-info/licenses/LICENSE'
adding 'topsis_anshika_102317059-1.0.0.dist-info/METADATA'
adding 'topsis_anshika_102317059-1.0.0.dist-info/WHEEL'
adding 'topsis_anshika_102317059-1.0.0.dist-info/entry_points.txt'
adding 'topsis_anshika_102317059-1.0.0.dist-info/top_level.txt'
adding 'topsis_anshika_102317059-1.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built topsis_anshika_102317059-1.0.0.tar.gz and topsis_anshika_102317059-1.0.0-py3-none-any.whl

In [ ]:
!pip install -q dist/*.whl

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Fund Name": ["M1","M2","M3"],
    "P1":[0.67,0.60,0.82],
    "P2":[0.45,0.36,0.67],
    "P3":[6.5,3.6,3.8]
})
df.to_csv("data.csv", index=False)

df

  Fund Name    P1    P2   P3
0        M1  0.67  0.45  6.5
1        M2  0.60  0.36  3.6
2        M3  0.82  0.67  3.8

In [ ]:
!topsis data.csv "1,1,1" "+,+,+" output-result.csv

TOPSIS completed ✅ Output saved to: output-result.csv

In [ ]:
!python -m twine upload -u __token__ -p "pypi-AgEIcHlwaS5vcmcCJDgyZjk5NjY0LWMzZTItNDRkMy04OWNhLWY3ZjUwNmJhMGQ5ZQACKlszLCI4MGIzZDgzMi01ZjY0LTQ0ZjgtYThiNy0yNjRmNzBjMGE4NTQiXQAABiC9ieOHT0ZR3oFPQFqq2f9OmA3yrNy9bT4zVAVVCo18XQ" dist/*

Uploading distributions to https://upload.pypi.org/legacy/
Uploading topsis_anshika_102317059-1.0.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 kB • 00:00 • ?
Uploading topsis_anshika_102317059-1.0.0.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 kB • 00:00 • ?

View at:
https://pypi.org/project/topsis-anshika-102317059/1.0.0/

In [ ]:
!python -m twine check dist/*

Checking dist/topsis_anshika_102317059-1.0.0-py3-none-any.whl: PASSED
Checking dist/topsis_anshika_102317059-1.0.0.tar.gz: PASSED

In [ ]:
!pip uninstall -y topsis-anshika-102317059

Found existing installation: topsis-anshika-102317059 1.0.0
Uninstalling topsis-anshika-102317059-1.0.0:
  Successfully uninstalled topsis-anshika-102317059-1.0.0

In [ ]:
!pip install topsis-anshika-102317059

Collecting topsis-anshika-102317059
  Downloading topsis_anshika_102317059-1.0.0-py3-none-any.whl.metadata (538 bytes)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from topsis-anshika-102317059) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from topsis-anshika-102317059) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->topsis-anshika-102317059) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->topsis-anshika-102317059) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->topsis-anshika-102317059) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->topsis-anshika-102317059) (1.17.0)
Downloading topsis_anshika_102317059-1.0.0-py3-none-any.whl (3.9 kB)
Installing collected packages: topsis-anshika-102317059
Successfully installed topsis-anshika-102317059-1.0.0

In [ ]:
!topsis data.csv "1,1,1" "+,+,+" output-result.csv

TOPSIS completed ✅ Output saved to: output-result.csv

In [ ]:
import pandas as pd
pd.read_csv("output-result.csv")

  Fund Name    P1    P2   P3  Topsis Score  Rank
0        M1  0.67  0.45  6.5        0.5689     1
1        M2  0.60  0.36  3.6        0.0000     3
2        M3  0.82  0.67  3.8        0.5500     2

In [ ]:
!pip install -q flask flask-ngrok pyngrok pandas numpy

In [ ]:
import os, shutil

if os.path.exists("topsis_web"):
    shutil.rmtree("topsis_web")

os.makedirs("topsis_web/templates", exist_ok=True)
os.makedirs("topsis_web/uploads", exist_ok=True)
os.makedirs("topsis_web/results", exist_ok=True)

print("Folders created ✅")

Folders created ✅

In [ ]:
%%writefile topsis_web/topsis_logic.py
import os
import pandas as pd
import numpy as np

class TopsisError(Exception):
    pass

def parse_weights_impacts(weights_str, impacts_str):
    if "," not in weights_str or "," not in impacts_str:
        raise TopsisError("Weights and Impacts must be separated by comma ','")

    weights = [w.strip() for w in weights_str.split(",")]
    impacts = [i.strip() for i in impacts_str.split(",")]

    try:
        weights = [float(w) for w in weights]
    except:
        raise TopsisError("Weights must be numeric and comma-separated.")

    for imp in impacts:
        if imp not in ["+", "-"]:
            raise TopsisError("Impacts must be either '+' or '-' only.")

    return weights, impacts

def run_topsis(input_file, weights_str, impacts_str, output_file):
    if not os.path.exists(input_file):
        raise TopsisError("File not found.")

    df = pd.read_csv(input_file)

    if df.shape[1] < 3:
        raise TopsisError("Input file must contain three or more columns.")

    data = df.iloc[:, 1:].copy()
    n_cols = data.shape[1]

    weights, impacts = parse_weights_impacts(weights_str, impacts_str)

    if len(weights) != n_cols or len(impacts) != n_cols:
        raise TopsisError("Number of weights, impacts and criteria columns must be same.")

    for col in data.columns:
        try:
            data[col] = pd.to_numeric(data[col])
        except:
            raise TopsisError(f"Non-numeric values found in column: {col}")

    matrix = data.to_numpy(dtype=float)

    norm = np.sqrt((matrix ** 2).sum(axis=0))
    if np.any(norm == 0):
        raise TopsisError("A column contains all zeros.")

    normalized = matrix / norm
    weighted = normalized * np.array(weights)

    ideal_best = np.zeros(n_cols)
    ideal_worst = np.zeros(n_cols)

    for j in range(n_cols):
        if impacts[j] == "+":
            ideal_best[j] = np.max(weighted[:, j])
            ideal_worst[j] = np.min(weighted[:, j])
        else:
            ideal_best[j] = np.min(weighted[:, j])
            ideal_worst[j] = np.max(weighted[:, j])

    dist_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    score = dist_worst / (dist_best + dist_worst)
    rank = score.argsort()[::-1] + 1

    df["Topsis Score"] = score.round(4)
    df["Rank"] = rank

    df.to_csv(output_file, index=False)
    return output_file

Writing topsis_web/topsis_logic.py

In [ ]:
%%writefile topsis_web/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>TOPSIS Web Service</title>
    <style>
        body { font-family: Arial; margin: 40px; }
        .box { width: 520px; border: 1px solid #aaa; padding: 20px; }
        label { display: inline-block; width: 120px; font-weight: bold; }
        input { width: 320px; padding: 6px; margin: 8px 0; }
        button { background: orange; padding: 10px 20px; border: 0; font-weight: bold; cursor: pointer; }
        .msg { margin-top: 15px; padding: 10px; }
        .ok { background: #d4edda; }
        .err { background: #f8d7da; }
    </style>
</head>
<body>
    <h2>TOPSIS Web Service</h2>

    <div class="box">
        <form method="POST" action="/submit" enctype="multipart/form-data">
            <div>
                <label>File Name</label>
                <input type="file" name="file" required>
            </div>

            <div>
                <label>Weights</label>
                <input type="text" name="weights" placeholder="1,1,1,1" required>
            </div>

            <div>
                <label>Impacts</label>
                <input type="text" name="impacts" placeholder="+,+,-,+" required>
            </div>

            <div>
                <label>Email Id</label>
                <input type="text" name="email" placeholder="example@gmail.com" required>
            </div>

            <div style="text-align:center;">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>

    {% if message %}
      <div class="msg {{ 'ok' if success else 'err' }}">
        {{ message }}
      </div>
    {% endif %}
</body>
</html>

Writing topsis_web/templates/index.html

In [ ]:
%%writefile topsis_web/mailer.py
import smtplib
from email.message import EmailMessage
import os

def send_email_with_attachment(receiver_email, subject, body, attachment_path, sender_email, sender_password):
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg.set_content(body)

    with open(attachment_path, "rb") as f:
        file_data = f.read()
        file_name = os.path.basename(attachment_path)

    msg.add_attachment(file_data, maintype="application", subtype="octet-stream", filename=file_name)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender_email, sender_password)
        smtp.send_message(msg)

Writing topsis_web/mailer.py

In [ ]:
%%writefile topsis_web/app.py
import os
import re
from flask import Flask, render_template, request
from topsis_logic import run_topsis, TopsisError
from mailer import send_email_with_attachment

app = Flask(__name__)

UPLOAD_FOLDER = "uploads"
RESULT_FOLDER = "results"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(RESULT_FOLDER, exist_ok=True)

# ✅ Secure: Read from Environment Variables
SENDER_EMAIL = os.environ.get("SENDER_EMAIL")
SENDER_APP_PASSWORD = os.environ.get("SENDER_APP_PASSWORD")

def valid_email(email):
    pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    return re.match(pattern, email)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/submit", methods=["POST"])
def submit():
    try:
        file = request.files.get("file")
        weights = request.form.get("weights", "")
        impacts = request.form.get("impacts", "")
        email = request.form.get("email", "")

        if not file or file.filename.strip() == "":
            return render_template("index.html", message="Please upload a CSV file.", success=False)

        if not valid_email(email):
            return render_template("index.html", message="Invalid email format.", success=False)

        if not SENDER_EMAIL or not SENDER_APP_PASSWORD:
            return render_template("index.html", message="Server email credentials are missing.", success=False)

        input_path = os.path.join(UPLOAD_FOLDER, file.filename)
        file.save(input_path)

        output_path = os.path.join(RESULT_FOLDER, "topsis_result.csv")

        run_topsis(input_path, weights, impacts, output_path)

        send_email_with_attachment(
            receiver_email=email,
            subject="TOPSIS Result File",
            body="Hi,\n\nAttached is your TOPSIS result file.\n\nThanks!",
            attachment_path=output_path,
            sender_email=SENDER_EMAIL,
            sender_password=SENDER_APP_PASSWORD
        )

        return render_template("index.html", message="Success ✅ Result file sent to your email.", success=True)

    except TopsisError as e:
        return render_template("index.html", message=f"Error: {str(e)}", success=False)

    except Exception as e:
        return render_template("index.html", message=f"Unexpected Error: {str(e)}", success=False)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)

Overwriting topsis_web/app.py

In [ ]:
import os
os.chdir("/content/topsis-anshika-102317059/topsis_web")
print("✅ Current folder:", os.getcwd())
!ls

✅ Current folder: /content/topsis-anshika-102317059/topsis_web
app.py	mailer.py  results  templates  topsis_logic.py	uploads

In [ ]:
!pip install -q pyngrok

In [ ]:
from pyngrok import ngrok

ngrok.set_auth_token("PASTE_TOKEN_HERE")
print("✅ Ngrok token set")